[package]
authors = ["oSumAtrIX"]
description = "The official Discord bot assisting the ReVanced Discord server"
homepage = "https://revanced.app"
keywords = ["ReVanced"]
license = "GPL-3.0"
name = "revanced-discord-bot"
repository = "https://github.com/revanced/revanced-discord-bot"
version = "1.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
poise = "0.3.0"
decancer = "1.4.1" # todo
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.0"
serde_regex = "1.1"
chrono = "0.4"
dirs = "4.0.0"
tracing = { version = "0.1", features = ["max_level_debug", "release_max_level_info"] }
tracing-subscriber = "0.3"